application: yourapp
version: version
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- warmup

libraries:
- name: django
  version: "1.4"
- name: PIL
  version: latest
- name: lxml
  version: latest
- name: yaml
  version: latest

builtins:
- django_wsgi: on


handlers:
- url: /static
  static_dir: static
  expiration: "0"

- url: /templates
  static_dir: application/templates
  secure: always

- url: /favicon\.ico
  static_files: static/core/img/favicon.ico
  upload: static/core/img/favicon\.ico

- url: /extadmin/.*
  script: google.appengine.ext.admin.application
  login: admin
